# -*- coding: utf-8 -*-
print("=" * 60)
print("  GitHub ????")
print("=" * 60)
print()
print("????: D:\\github\\pubmed-researcher")
print("Git ??: ? commit?????")
print()
print("?? A: GitHub CLI (??)")
print("  1. ??: https://cli.github.com/")
print("  2. gh auth login")
print("  3. gh repo create pubmed-researcher --public --source=. --push")
print()
print("?? B: ????")
print("  1. https://github.com/new -> pubmed-researcher -> Public")
print("  2. git remote add origin https://github.com/?????/pubmed-researcher.git")
print("  3. git branch -M main")
print("  4. git push -u origin main")
print()
print("5. ?? Sponsors: https://github.com/sponsors/?????")
print("=" * 60)
