path = r'D:\github\pubmed-researcher\bug_bounty_guide.md'
lines = []
lines.append('# Bug Bounty Earning Guide')
lines.append('')
lines.append('## Top Platforms')
lines.append('')
lines.append('### 1. HackerOne')
lines.append('URL: https://hackerone.com')
lines.append('Bounties: ' + chr(36) + '50 - ' + chr(36) + '100,000+ per bug')
lines.append('')
lines.append('### 2. Bugcrowd')
lines.append('URL: https://bugcrowd.com')
lines.append('Bounties: ' + chr(36) + '100 - ' + chr(36) + '50,000+ per bug')
lines.append('')
lines.append('### 3. Open Bug Bounty (Easiest)')
lines.append('URL: https://openbugbounty.org')
lines.append('Bounties: ' + chr(36) + '10 - ' + chr(36) + '500 per bug')
lines.append('')
lines.append('### 4. Intigriti (Europe)')
lines.append('URL: https://intigriti.com')
lines.append('Bounties: ' + chr(36) + '50 - ' + chr(36) + '10,000 per bug')
lines.append('')
lines.append('## 5 Common Beginner Bugs')
lines.append('')
lines.append('1. XSS - ' + chr(36) + '100 to ' + chr(36) + '5,000')
lines.append('2. Info Disclosure - ' + chr(36) + '50 to ' + chr(36) + '1,000')
lines.append('3. IDOR - ' + chr(36) + '500 to ' + chr(36) + '10,000')
lines.append('4. API Keys - ' + chr(36) + '1,000 to ' + chr(36) + '50,000')
lines.append('5. Business Logic - ' + chr(36) + '500 to ' + chr(36) + '10,000')
lines.append('')
lines.append('## 30-Day Path')
lines.append('Week 1: Register HackerOne/Bugcrowd, study OWASP Top 10, practice on portswigger.net')
lines.append('Week 2: Start Open Bug Bounty, test small sites')
lines.append('Week 3-4: Submit reports, get first ' + chr(36) + '50-200')
lines.append('')
lines.append('## Your Medical Edge')
lines.append('- Medical bug bounties: ' + chr(36) + '5,000 to ' + chr(36) + '100,000')
lines.append('- Less competition in healthcare')
lines.append('- Target: Hospital systems, Medical AI, PubMed-like databases')
lines.append('')
lines.append('## Timeline')
lines.append('| Month | Earnings |')
lines.append('|-------|----------|')
lines.append('| 1-2 | ' + chr(36) + '0 learning |')
lines.append('| 3-4 | ' + chr(36) + '50-' + chr(36) + '200 |')
lines.append('| 6 | ' + chr(36) + '500-' + chr(36) + '2000/month |')
lines.append('| 12 | ' + chr(36) + '3000-' + chr(36) + '10000/month |')
lines.append('')
lines.append('## Chinese Resources')
lines.append('- https://xz.aliyun.com')
lines.append('- https://www.vulbox.com')
with open(path, 'w', encoding='utf-8') as f:
    f.write(chr(10).join(lines))
print('OK')
